kind = "api"
previewPath = "/hunter"
title = "Meme Coin Hunter"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8099
name = "Meme Coin Hunter"
paths = ["/hunter"]

[services.development]
run = "cd hunter && PORT=8099 go run ."
